galaxy_info:
  author: Julien M'Poy
  description: A base role to install a minimum of softwares on a Debian server
  license: MIT

  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  platforms:
    - name: Debian
      versions:
      - all
      - 9

  galaxy_tags: ['debian', 'server']

dependencies: []
